In [1]:
import numpy
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.utils import np_utils

/home/hywel/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
# define the raw dataset
alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
# create mapping of characters to integers (0-25) and the reverse
char_to_int = dict((c, i) for i, c in enumerate(alphabet))
int_to_char = dict((i, c) for i, c in enumerate(alphabet))

In [4]:
# prepare the dataset of input to output pairs encoded as integers
seq_length = 3
dataX = []
dataY = []
for i in range(0, len(alphabet) - seq_length, 1):
    seq_in = alphabet[i:i + seq_length]
    seq_out = alphabet[i + seq_length]
    dataX.append([char_to_int[char] for char in seq_in])
    dataY.append(char_to_int[seq_out])
    print (seq_in, '->', seq_out)

ABC -> D
BCD -> E
CDE -> F
DEF -> G
EFG -> H
FGH -> I
GHI -> J
HIJ -> K
IJK -> L
JKL -> M
KLM -> N
LMN -> O
MNO -> P
NOP -> Q
OPQ -> R
PQR -> S
QRS -> T
RST -> U
STU -> V
TUV -> W
UVW -> X
VWX -> Y
WXY -> Z


In [6]:
# reshape X to be [samples, time steps, features]
X = numpy.reshape(dataX, (len(dataX), 1, seq_length))
y = np_utils.to_categorical(dataY)

print (X)


[[[ 0  1  2]]

 [[ 1  2  3]]

 [[ 2  3  4]]

 [[ 3  4  5]]

 [[ 4  5  6]]

 [[ 5  6  7]]

 [[ 6  7  8]]

 [[ 7  8  9]]

 [[ 8  9 10]]

 [[ 9 10 11]]

 [[10 11 12]]

 [[11 12 13]]

 [[12 13 14]]

 [[13 14 15]]

 [[14 15 16]]

 [[15 16 17]]

 [[16 17 18]]

 [[17 18 19]]

 [[18 19 20]]

 [[19 20 21]]

 [[20 21 22]]

 [[21 22 23]]

 [[22 23 24]]]


In [7]:
# create and fit the model
model = Sequential()
model.add(LSTM(32, input_shape=(X.shape[1], X.shape[2])))
model.add(Dense(y.shape[1], activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, nb_epoch=500, batch_size=1, verbose=2)

/home/hywel/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/500
 - 1s - loss: 3.3248 - acc: 0.0435
Epoch 2/500
 - 0s - loss: 3.2510 - acc: 0.0435
Epoch 3/500
 - 0s - loss: 3.2106 - acc: 0.0435
Epoch 4/500
 - 0s - loss: 3.1758 - acc: 0.0435
Epoch 5/500
 - 0s - loss: 3.1450 - acc: 0.0435
Epoch 6/500
 - 0s - loss: 3.1142 - acc: 0.0435
Epoch 7/500
 - 0s - loss: 3.0852 - acc: 0.0435
Epoch 8/500
 - 0s - loss: 3.0577 - acc: 0.1304
Epoch 9/500
 - 0s - loss: 3.0313 - acc: 0.0870
Epoch 10/500
 - 0s - loss: 3.0113 - acc: 0.1304
Epoch 11/500
 - 0s - loss: 2.9874 - acc: 0.1304
Epoch 12/500
 - 0s - loss: 2.9601 - acc: 0.0870
Epoch 13/500
 - 0s - loss: 2.9395 - acc: 0.1304
Epoch 14/500
 - 0s - loss: 2.9186 - acc: 0.0870
Epoch 15/500
 - 0s - loss: 2.8970 - acc: 0.1304
Epoch 16/500
 - 0s - loss: 2.8738 - acc: 0.1739
Epoch 17/500
 - 0s - loss: 2.8555 - acc: 0.1739
Epoch 18/500
 - 0s - loss: 2.8313 - acc: 0.2174
Epoch 19/500
 - 0s - loss: 2.8054 - acc: 0.2174
Epoch 20/500
 - 0s - loss: 2.7890 - acc: 0.1304
Epoch 21/500
 - 0s - loss: 2.7685 - acc: 0.2174
E

Epoch 171/500
 - 0s - loss: 1.8325 - acc: 0.5652
Epoch 172/500
 - 0s - loss: 1.8247 - acc: 0.4783
Epoch 173/500
 - 0s - loss: 1.8269 - acc: 0.4783
Epoch 174/500
 - 0s - loss: 1.8221 - acc: 0.5217
Epoch 175/500
 - 0s - loss: 1.8192 - acc: 0.4348
Epoch 176/500
 - 0s - loss: 1.8254 - acc: 0.4783
Epoch 177/500
 - 0s - loss: 1.8194 - acc: 0.4783
Epoch 178/500
 - 0s - loss: 1.8107 - acc: 0.4783
Epoch 179/500
 - 0s - loss: 1.8075 - acc: 0.4348
Epoch 180/500
 - 0s - loss: 1.8089 - acc: 0.5217
Epoch 181/500
 - 0s - loss: 1.7997 - acc: 0.5652
Epoch 182/500
 - 0s - loss: 1.8034 - acc: 0.5652
Epoch 183/500
 - 0s - loss: 1.8055 - acc: 0.5217
Epoch 184/500
 - 0s - loss: 1.7982 - acc: 0.5217
Epoch 185/500
 - 0s - loss: 1.7917 - acc: 0.5652
Epoch 186/500
 - 0s - loss: 1.7877 - acc: 0.5652
Epoch 187/500
 - 0s - loss: 1.7901 - acc: 0.7391
Epoch 188/500
 - 0s - loss: 1.7840 - acc: 0.3913
Epoch 189/500
 - 0s - loss: 1.7858 - acc: 0.6522
Epoch 190/500
 - 0s - loss: 1.7766 - acc: 0.5652
Epoch 191/500
 - 0s 

 - 0s - loss: 1.5085 - acc: 0.7391
Epoch 339/500
 - 0s - loss: 1.5174 - acc: 0.8696
Epoch 340/500
 - 0s - loss: 1.4964 - acc: 0.8261
Epoch 341/500
 - 0s - loss: 1.5080 - acc: 0.8261
Epoch 342/500
 - 0s - loss: 1.5006 - acc: 0.6957
Epoch 343/500
 - 0s - loss: 1.5073 - acc: 0.6957
Epoch 344/500
 - 0s - loss: 1.4972 - acc: 0.6957
Epoch 345/500
 - 0s - loss: 1.4894 - acc: 0.7826
Epoch 346/500
 - 0s - loss: 1.4998 - acc: 0.8261
Epoch 347/500
 - 0s - loss: 1.4983 - acc: 0.8261
Epoch 348/500
 - 0s - loss: 1.4907 - acc: 0.8261
Epoch 349/500
 - 0s - loss: 1.4898 - acc: 0.6522
Epoch 350/500
 - 0s - loss: 1.4902 - acc: 0.7391
Epoch 351/500
 - 0s - loss: 1.4847 - acc: 0.7391
Epoch 352/500
 - 0s - loss: 1.4907 - acc: 0.6522
Epoch 353/500
 - 0s - loss: 1.4848 - acc: 0.9130
Epoch 354/500
 - 0s - loss: 1.4828 - acc: 0.8261
Epoch 355/500
 - 0s - loss: 1.4790 - acc: 0.6957
Epoch 356/500
 - 0s - loss: 1.4775 - acc: 0.6957
Epoch 357/500
 - 0s - loss: 1.4917 - acc: 0.7826
Epoch 358/500
 - 0s - loss: 1.4828